[build]
base    = "jiwon-saas"
publish = ".next"
command = "npm run build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions."cron-sync-subsidies"]
schedule = "0 0 * * *"

[functions."cron-send-notifications"]
schedule = "0 1 * * *"

[functions."cron-billing"]
schedule = "0 0 1 * *"
